### ISSUE TITLE
Improve settings in IVA to be more user-specific

### ISSUE THREAD

**Issue by Swaathik** [opencb/iva#18]
It would be good to allow users to customise things like consequence type, population frequency colors if they need to do and store their own configuration.

**Comment by imedina** [comment]
Current implementation looks like this:

![image](https://cloud.githubusercontent.com/assets/1427327/19308168/271f9846-9076-11e6-9c71-949bf1dcebf1.png)

I'm leaving this open a few days more to be reviewed
