### ISSUE TITLE
The project-study status line is covered by the header when header text takes more than one line

### ISSUE THREAD

**Issue by pamag** [opencb/iva#194]
![image](https://user-images.githubusercontent.com/167875/54222124-10bcdd80-44f5-11e9-83c1-7a89abbc5815.png)
If the text in header does not fit in one line and takes more lines, the project/study status line gets covered by the heder .

Also the transition to mobile is done in two steps, firsta table space go below the left panel, but all text in header remains as before

![image](https://user-images.githubusercontent.com/167875/54222609-0c44f480-44f6-11e9-85ee-b1913a1c5220.png)

and then at some point if the width becomes smaller a hamburger appear

![image](https://user-images.githubusercontent.com/167875/54222683-2c74b380-44f6-11e9-9176-beb025207aaa.png)

**Comment by antonioaltamura** [comment]
This issue is related to IVA 1.x. IVA 2+ fixed it.
