### ISSUE TITLE
Prepending http to https domain?

### ISSUE THREAD

**Issue by sm766** [opencb/iva#30]
Hi,

Is it possible to run IVA over https? IVA appears to prepend 'http' to a bare host name entered in config.js. I'm on the 'develop' branch; The returned error in the browser console (both Chrome and Firefox tested on Linux) is:

> Mixed Content: The page at 'https://mydomain.com/iva/#home' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mydomain.com/opencga/webservices/rest/v1/files/bioformats'. This request has been blocked; the content must be served over HTTPS.

Any help would be appreciated.

**Comment by Swaathik** [comment]
Hi,

I found that it is hard-coded to prepend "http://" when the call to rest web service is made. I will fix it as soon as possible and I will let you know.

**Comment by Swaathik** [comment]
Can you please pull the develop branch and see everything works as expected? Please update the submodule as well. Can you let me know if it is solved?

**Comment by sm766** [comment]
Thanks.

I pulled and rebuilt the client which sort of worked (although perhaps not as a long term solution) in the sense that I can now log in to IVA as expected with an https configured opencga host. However mixed content errors persist due to the cellbase host dependency over http (I don't have a local instance exposed over https). Attached are the logs generated from the debugging console while searching for a gene in the variant browser, `mydomain.com` replaces my actual domain. 

The http/https mixed content gotchas will require code to be transport protocol agnostic throughout the implementation. There are some typing errors further down the logs but perhaps these are related to the cellbase host being blocked? I can open a new issue if you think these are unrelated.

[mydomain.com-1482230968924.txt](https://github.com/opencb/iva/files/663532/mydomain.com-1482230968924.txt)

Thanks again.

**Comment by imedina** [comment]
We have recently start migrating CellBase and the other servers to HTTPS, the migration should be finished for the end of the week, then you can just write https in the domains:

var cellbase = {
    hosts: ["https://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-rc"],
    version: "v4"
};

var opencga = {
    host: "https://bioinfodev.hpc.cam.ac.uk/hgva-1.0.0",
    ...
}

I will inform of this.
