### ISSUE TITLE
Keep displaying variants with missing values for a particular filter

### ISSUE THREAD

**Issue by sg550** [opencb/iva#54]
Please make sure that variants are still shown, if the filter value is not set/calculated.

For example, if I want to filter variants in a gene with a CADD of 15 or higher I would also like to see those INDELs that do not have a CADD score calculated. 

Or, if I want to filter all variants with a CADD score of 15 or higher and with SIFT being deleterious or PolyPhen being damaging, I would also like to see all the nonsense variants (stop_gained, frameshift, etc.) that never have a SIFT or PolyPhen value set, but very high CADD scores. Currently only missense variants are displayed with such a filter.

Similarly this should be applied to minor allele frequency filters.

**Comment by imedina** [comment]
This is a nice request, thanks!
